/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CaseStudy;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author willi
 */
public class choiceByTypeRoom extends javax.swing.JFrame {

    resultListRoomByTypeRoom resultListRoomByTypeRoom = new resultListRoomByTypeRoom();

    /**
     * Creates new form resultByTypeRoom
     */
    public choiceByTypeRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Standard = new javax.swing.JButton();
        Deluxe = new javax.swing.JButton();
        Bungalow = new javax.swing.JButton();
        President = new javax.swing.JButton();
        Suite = new javax.swing.JButton();
        RoyalSuite = new javax.swing.JButton();
        backToMenu = new javax.swing.JButton();
        Superior = new javax.swing.JButton();

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CaseStudy/image/1_1.png"))); // NOI18N

        Standard.setText("Standard");
        Standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardActionPerformed(evt);
            }
        });

        Deluxe.setText("Deluxe");
        Deluxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeluxeActionPerformed(evt);
            }
        });

        Bungalow.setText("Bungalow");
        Bungalow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BungalowActionPerformed(evt);
            }
        });

        President.setText("President");
        President.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresidentActionPerformed(evt);
            }
        });

        Suite.setText("Suite");
        Suite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuiteActionPerformed(evt);
            }
        });

        RoyalSuite.setText("RoyalSuite");
        RoyalSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoyalSuiteActionPerformed(evt);
            }
        });

        backToMenu.setText("Menu");
        backToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuActionPerformed(evt);
            }
        });

        Superior.setText("Superior");
        Superior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuperiorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Deluxe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Standard, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bungalow, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(President, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoyalSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suite, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Superior, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Standard, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Superior, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deluxe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Suite, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(President, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoyalSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bungalow, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StandardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardActionPerformed
        // TODO add your handling code here:
        resultListRoomByTypeRoom.setFillToTable("Standard");

        if (resultListRoomByTypeRoom.count <= 0) {
            JOptionPane.showMessageDialog(null, "Hạng phòng Standard chưa có khách nghỉ");
        } else {
            resultListRoomByTypeRoom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            resultListRoomByTypeRoom.setResizable(false);
            resultListRoomByTypeRoom.setVisible(true);
        }
    }//GEN-LAST:event_StandardActionPerformed

    private void SuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuperiorActionPerformed
        // TODO add your handling code here:
        resultListRoomByTypeRoom.setFillToTable("Superior");

        if (resultListRoomByTypeRoom.count <= 0) {
            JOptionPane.showMessageDialog(null, "Hạng phòng Superior chưa có khách nghỉ");
        } else {
             resultListRoomByTypeRoom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            resultListRoomByTypeRoom.setResizable(false);
            resultListRoomByTypeRoom.setVisible(true);
        }
    }//GEN-LAST:event_SuperiorActionPerformed

    private void DeluxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeluxeActionPerformed
        // TODO add your handling code here:
        resultListRoomByTypeRoom.setFillToTable("Deluxe");

        if (resultListRoomByTypeRoom.count <= 0) {
            JOptionPane.showMessageDialog(null, "Hạng phòng Deluxe chưa có khách nghỉ");
        } else {
             resultListRoomByTypeRoom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            resultListRoomByTypeRoom.setResizable(false);
            resultListRoomByTypeRoom.setVisible(true);
        }
    }//GEN-LAST:event_DeluxeActionPerformed

    private void SuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuiteActionPerformed
        // TODO add your handling code here:
        resultListRoomByTypeRoom.setFillToTable("Suite");

        if (resultListRoomByTypeRoom.count <= 0) {
            JOptionPane.showMessageDialog(null, "Hạng phòng Suite chưa có khách nghỉ");
        } else {
             resultListRoomByTypeRoom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            resultListRoomByTypeRoom.setResizable(false);
            resultListRoomByTypeRoom.setVisible(true);
        }
    }//GEN-LAST:event_SuiteActionPerformed

    private void PresidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresidentActionPerformed
        // TODO add your handling code here:
        resultListRoomByTypeRoom.setFillToTable("President");

        if (resultListRoomByTypeRoom.count <= 0) {
            JOptionPane.showMessageDialog(null, "Hạng phòng President chưa có khách nghỉ");
        } else {
             resultListRoomByTypeRoom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            resultListRoomByTypeRoom.setResizable(false);
            resultListRoomByTypeRoom.setVisible(true);
        }

    }//GEN-LAST:event_PresidentActionPerformed

    private void RoyalSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoyalSuiteActionPerformed
        // TODO add your handling code here:
        resultListRoomByTypeRoom.setFillToTable("RoyalSuite");

        if (resultListRoomByTypeRoom.count <= 0) {
            JOptionPane.showMessageDialog(null, "Hạng phòng RoyalSuite chưa có khách nghỉ");
        } else {
             resultListRoomByTypeRoom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            resultListRoomByTypeRoom.setResizable(false);
            resultListRoomByTypeRoom.setVisible(true);
        }

    }//GEN-LAST:event_RoyalSuiteActionPerformed

    private void BungalowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BungalowActionPerformed
        // TODO add your handling code here:
        resultListRoomByTypeRoom.setFillToTable("Bungalow");

        if (resultListRoomByTypeRoom.count <= 0) {
            JOptionPane.showMessageDialog(null, "Hạng phòng Bungalow chưa có khách nghỉ");
        } else {
             resultListRoomByTypeRoom.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            resultListRoomByTypeRoom.setResizable(false);
            resultListRoomByTypeRoom.setVisible(true);
        }

    }//GEN-LAST:event_BungalowActionPerformed

    private void backToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuActionPerformed
        // TODO add your handling code here:
        guiMenu guiMenu = new guiMenu();
        dispose();
        guiMenu.setResizable(false);
        guiMenu.setVisible(true);
    }//GEN-LAST:event_backToMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choiceByTypeRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choiceByTypeRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choiceByTypeRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choiceByTypeRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choiceByTypeRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bungalow;
    private javax.swing.JButton Deluxe;
    private javax.swing.JButton President;
    private javax.swing.JButton RoyalSuite;
    private javax.swing.JButton Standard;
    private javax.swing.JButton Suite;
    private javax.swing.JButton Superior;
    private javax.swing.JButton backToMenu;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
